# Generated by Django 5.0.1 on 2024-10-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_all_day",
            field=models.BooleanField(default=False),
        ),
    ]
