# Generated by Django 5.0.1 on 2024-10-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0003_alter_event_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="recurrence_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
